Document: epics-pmacutil-dev
Title: Debian epics-pmacutil-dev Manual
Author: <insert document author here>
Abstract: This manual describes what epics-pmacutil-dev is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/epics-pmacutil-dev/epics-pmacutil-dev.sgml.gz

Format: postscript
Files: /usr/share/doc/epics-pmacutil-dev/epics-pmacutil-dev.ps.gz

Format: text
Files: /usr/share/doc/epics-pmacutil-dev/epics-pmacutil-dev.text.gz

Format: HTML
Index: /usr/share/doc/epics-pmacutil-dev/html/index.html
Files: /usr/share/doc/epics-pmacutil-dev/html/*.html
